name: build

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: GitHub checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
            go-version: 1.19

      - name: Download
        working-directory: ./cmd
        run: go mod download

      - name: Build
        working-directory: ./cmd
        run: go build .

      - name: Vet
        working-directory: ./cmd
        run: go vet ./...

      - name: Test
        working-directory: ./cmd
        run: go test -v ./...

      - name: Docker Hub
        run: |
          cd ..
          docker login -u ${{ secrets.DOCKER_HUB_USER }} -p "${{ secrets.DOCKER_HUB_PASSWORD }}"
          docker build -t masoudkarimif/docker-lambda-deploy
          docker push masoudkarimif/docker-lambda-deploy:latest