name: lint

on:
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  run:
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: lint
      run: |
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.45.2
        golangci-lint run --deadline=3m